name: capung_id
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  camera: ^0.11.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  tflite_flutter: ^0.11.0
  image: ^4.5.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FECA5C"
  image: "assets/logosplash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/capung/
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/5.2.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/logo/logocapung.jpg
    - assets/logo/logo.webp
    - assets/logosplash.png
    - assets/capung_model.tflite
    - assets/labels.txt
    - assets/capung_model_v2.tflite